### ISSUE TITLE
Enhancement: Documentation for diff-coverage

### ISSUE THREAD

**Issue by alanmcruickshank** [alanmcruickshank/sqlfluff#105]
Following on from #85 - @barrywhart, are you able to write some documentation for the diff-coverage plugin you added? Just add a new `rst` file in the `docs/source` folder, and then reference them in an appropriate place in the `index.rst` contents section.

**Comment by barrywhart** [comment]
Sure, I'll write something up. Are you thinking of usage documentation or something deeper/more technical? I'll start with usage docs and look over the existing docs to get some context. I'll probably get to this in the next couple of days. I hope you had a nice holiday!

**Comment by alanmcruickshank** [comment]
I'm thinking entirely usage documentation. Something so that people know how to use the feature.

Bonus points for some technical extras if they're interesting - but I care much more about it being useful for new users.

**Comment by barrywhart** [comment]
I think this ticket can be closed now.
