### ISSUE TITLE
New rule: When defining a column or table alias, always include the AS keyword

### ISSUE THREAD

**Issue by barrywhart** [alanmcruickshank/sqlfluff#11]
This is more readable, as it makes the aliasing explicit.

**Comment by alanmcruickshank** [comment]
Great idea 👍

**Comment by alanmcruickshank** [comment]
At the moment I don't think queries which do this will even *parse*. Parsing this successfully will definitely be done before 0.2.0. I anticipate that this *might* be the first implemented rule which is *deactivated* by default, and I'm not sure yet how this fits into how sqlfluff will be *defaultly* opinionated. It seems like a very sensible option however.
