### ISSUE TITLE
Enhancement: Deprecating python 2.7 and python 3.4 support

### ISSUE THREAD

**Issue by alanmcruickshank** [alanmcruickshank/sqlfluff#115]
Currently we support python 2.7 and python 3.4, both of which are past their maintenance horizon: https://python-release-cycle.glitch.me/

This has come up in a few bug previously, and I think the time has come to sunset support for those versions.

Proposal:
- Support for python 2.7 and 3.4 is dropped with a major version upgrade 0.2.x > 0.3.x.
- The 0.2.x branch is still available for use if people wish to contribute to it, but it won't be actively maintained and new features will not be back-ported to it.
- A page in the documentation will be built to detail which python versions are supported by which major versions of sqlfluff.

@barrywhart @mrshu @nolanbconaway - does this cause any major issues for you guys?

**Comment by barrywhart** [comment]
We still have a few projects on Python 2.7, but none of them are using this project, so I think we're fine.

**Comment by nolanbconaway** [comment]
Sounds good to me! I think its entirely good practice to drop support given that the tool is still in an alpha phase

**Comment by Doldge** [comment]
issue title is typo'd, say's python3.7 and python3.4 instead of python2.7 and python3.4

**Comment by alanmcruickshank** [comment]
@Doldge - crap. Right you are 🤦‍♂

**Comment by alanmcruickshank** [comment]
Closed in #116
