### ISSUE TITLE
Parse error with `JOIN ON`

### ISSUE THREAD

**Issue by mrshu** [alanmcruickshank/sqlfluff#159]
Hey @alanmcruickshank,

Kudos on all the new improvements!

I've been trying out version `0.2.4` and it turns out the following SQL file

```sql
SELECT
    t1.id AS id,
    t1.text AS text,
    t2.attribute AS attribute
FROM
    t1
JOIN
    t2 ON t1.id = t2.id
```

finishes with the following error:

```
== [/tmp/a.sql] FAIL
L:   8 | P:   8 | ???? | Found unparsable segment @L008P008: 'ON t1.id = t2.id\n...'
```

If you could point me to where sqlfluff handles stuff like this, I'd be happy to help with fixing it.

Thanks!

**Comment by alanmcruickshank** [comment]
thanks @mrshu - are you on the latest release or on the master branch? I think this might be fixed already on master.

**Comment by mrshu** [comment]
Sorry, I tried out the `0.2.4` release -- will check the `master` branch right away.

**Comment by mrshu** [comment]
Thanks @alanmcruickshank -- this does indeed work in `master`.
