### ISSUE TITLE
Bug: Unparsable statement "online_sales / 1000.0"

### ISSUE THREAD

**Issue by mrshu** [alanmcruickshank/sqlfluff#161]
Running `sqlfluff lint` (installed from current `master`) on the following query

```sql
SELECT
    CAST(ROUND(online_sales / 1000.0) AS varchar) AS result
FROM sales
```

results in the following stack trace

```
L:   2 | P:  16 |  PRS | Found unparsable segment @L002P016: 'online_sales / 1000....'
```

Once again, happy to help debug this some further!

**Comment by guillermo-menjivar** [comment]
I just hit the same issue here - not sure why the CAST function is unparsable

**Comment by guillermo-menjivar** [comment]
should this not have an additional definition for the cast function https://github.com/alanmcruickshank/sqlfluff/blob/c3b61b33544bf5c9b89651254067715067b3eb78/src/sqlfluff/dialects/dialect_ansi.py#L38
can you correct me @alanmcruickshank

**Comment by guillermo-menjivar** [comment]
just trying to figure what it takes to compose a PR to get this issue resolved

**Comment by mrshu** [comment]
@guillermo-menjivar I am afraid that will require setting up a specific segment. Looking at the [list of subexpressions](https://www.cockroachlabs.com/docs/stable/sql-grammar.html#func_expr_common_subexpr) it seems pretty much all of them could benefit from something like this in one way or the other.

**Comment by alanmcruickshank** [comment]
I think this is fixed on master too - looks like I've left it waaaay to long before publishing a new version. I'll aim to get a release out and then reassess this bug.

**Comment by mrshu** [comment]
@alanmcruickshank I am afraid that is not so -- I've just installed `sqlfluff` using the following

```
pip install git+https://github.com/alanmcruickshank/sqlfluff.git@1744583820adb3174e7862549f6621853e8e4a8d --upgrade

```
where 1744583820adb3174e7862549f6621853e8e4a8d is the last commit hash.

Sadly, the result seems to be the same.
