### ISSUE TITLE
Bug: Found unparsable segment @L002P007: 'id*1.0/id > 0.8...'

### ISSUE THREAD

**Issue by mrshu** [alanmcruickshank/sqlfluff#178]
On latest `master`, linting the following query

```sql
SELECT * FROM test
WHERE id*1.0/id > 0.8;
```

results into the following parsing issue:

```
L:   2 | P:   7 |  PRS | Found unparsable segment @L002P007: 'id*1.0/id > 0.8...'
```

It seems to be valid SQL: https://www.db-fiddle.com/f/vDW3ejhcEAcV2FprHSNaU6/0

Please let me know if I can be of some more help!

**Comment by alanmcruickshank** [comment]
I've added a fix for this to PR #177
