### ISSUE TITLE
Bug: Found unparsable segment @L001P008: 't.val/t.id...'

### ISSUE THREAD

**Issue by mrshu** [alanmcruickshank/sqlfluff#179]
On latest `master`, linting the following query

```sql
SELECT t.val/t.id
FROM test AS t;
```

results into the following parsing issue:

```
L:   1 | P:   8 |  PRS | Found unparsable segment @L001P008: 't.val/t.id...'
```

It seems to be valid SQL: https://www.db-fiddle.com/f/fVtxCagWabyqZBUhzm2Nva/1

Please let me know if I can be of some more help!

**Comment by alanmcruickshank** [comment]
I've added a fix for this to PR #177
