### ISSUE TITLE
PRS Error: Found unparsable segment @L001P008: 'a.b.*...'

### ISSUE THREAD

**Issue by Dandandan** [alanmcruickshank/sqlfluff#187]
SQL query to reproduce:
```sql
SELECT a.b.* FROM t
```

**Comment by alanmcruickshank** [comment]
Thanks @Dandandan . I think things are set up to allow `a.b.c` and `a.c`, but not `a.b.*`. Thanks for raising!

**Comment by Dandandan** [comment]
Thanks for checking this so quickly! Does the fix also parse any number of nesting though? a.b.c.* a.b.c.d.* , etc?
