### ISSUE TITLE
Enhancement: Performance is too slow on long queries

### ISSUE THREAD

**Issue by alanmcruickshank** [alanmcruickshank/sqlfluff#189]
We've not worked much on performance yet, but on long queries, performance is very slow now.

- We need a way of monitoring performance, maybe through circleci?
- It looks like the algorithm for matching on long segment strings is the main issue, so a way of shortcutting this matching process, perhaps using hashes might help here.

**Comment by pwildenhain** [comment]
From what I've noticed, the parse is _much_ ⚡ faster now than before, even with long queries

**Comment by alanmcruickshank** [comment]
Thanks @pwildenhain - there are some of the larger queries that it still doesn't parse in a reasonable timeframe, which means there's more work to do here. Glad to hear whatever I'm doing is working though!! 😄
