### ISSUE TITLE
Unexpected indentation rules in the FROM

### ISSUE THREAD

**Issue by cnolanminich** [alanmcruickshank/sqlfluff#232]
❤️  this project! I've been taking it for a spin (with the hopes of using it in our CI pipelines for our SQL transforms).

One unexpected behavior is that subsequent joins are required to be on the same level of indentation as the keywords, *not* the same level of indentation of the preceding table,

test.sql:
```sql
select *
from
    table_1
    inner join table_2 on table_2.join_key = table_1.join_key

```
throws 
> `indentation not consistent with line 1`.  

The only way to satisfy that rule is to put the `inner join` on the same indentation row as the `from` segment:

test.sql:
```sql
select *
from
    table_1
inner join table_2 on table_2.join_key = table_1.join_key

```

This is not what I would expect -- the `inner join` should belong on the same indentation as `table_1`.

FYI, I tested this on a re-built version from the `master` branch this morning.

**Comment by alanmcruickshank** [comment]
@cnolanminich thanks for trying out the project! I'm glad you like it.

We had a discussion about *exactly* this case a few months ago. In the end we sided with the most commonly used style guides at the moment which prefer the latter formulation:
- https://docs.telemetry.mozilla.org/concepts/sql_style.html#joins
- https://github.com/fishtown-analytics/corp/blob/master/dbt_coding_conventions.md

I'm open to this being configurable however if you've got a large codebase with the former version. IMHO the first version *is* more technically correct, it's just not the most common.

Are you aware of any public style guides which prefer your suggested indentation? I'd love to link to them if you are.

**Comment by cnolanminich** [comment]
Thanks! Tbh it just seemed so apparently right that I’d never bothered to check before. 

We do have a big code base (no public style guide at the moment). 

I’ll hunt for some good references and see if I can find any).

**Comment by cnolanminich** [comment]
I found this reference from Baron Schwartz [here](https://www.xaprb.com/blog/2006/04/26/sql-coding-standards/):

> When I write a clause that is part of another clause, I indent it as well. For example, JOINs are part of the FROM clause, so they should be indented after the first line:
```sql
select column ...
from ...
    inner join ...
    inner join ...
    left outer join ...
where ...
group by ...
order by ...
```
I wouldn't quite call it a "style guide," but it has the major components (and it describes conclusions very close to where my team arrived in our own internal style guide).

I also found this http://www.dpriver.com/pp/sqlformat.htm SQL formatter that follows the JOIN indent convention I'm advocating for here, though I can't find a style guide for it.

**Comment by alanmcruickshank** [comment]
iiiinteresting. I'm open to a configurable indentation strategy for this, so this could be a feature which you could switch on or off. Thanks for the links!

I think I would build this out like a set of feature flags, probably as a subset of the core config. This particular example would be the `indented_joins` feature, which defaults to `False` but can be set to `True` for people with similar requirements to yours.

How would that sound?

**Comment by cnolanminich** [comment]
That sounds perfect 🚀. Thanks for considering!

**Comment by cnolanminich** [comment]
My other thought is — perhaps the rules for indentation could be split up? I haven’t looked at whether that’s tractable within the code, but it might be a way to customize the indentation selections

**Comment by cnolanminich** [comment]
@alanmcruickshank  🎉  It worked like a charm. I installed from the branch, followed your config, and testing on my simple `test.sql`

```sql
select *
from
    table_1
    inner join table_2 on table_2.join_key = table_1.join_key
```

As well as on 2 production SQL queries (with CTEs, etc), and verified that it worked (and that it correctly flagged as lint the non-indented JOINs when I set [sqlfluff:indentation]
indented_joins = True
