### ISSUE TITLE
Parser hangs on simple script with leading comma before column expression

### ISSUE THREAD

**Issue by barrywhart** [alanmcruickshank/sqlfluff#234]
I've run `sqlfluff fix --rules L003,L005` on a couple of our data science projects. In both cases, it prints a count of the number of issues it found and asks if I want it to fix them. In both cases, when I answer yes, it runs for a very long time with no output (other than, in one case, the debugging output I mentioned in #233). I have waited as much as 30 minutes.

I don't know if it's completely stuck or just very slow. Since I'm running it on a whole directory, I don't know if it's one particular file causing a problem or more of a general problem. Any thoughts on how we can start to narrow down the potential issue?

**Comment by barrywhart** [comment]
If I run it using just L003, it finishes without hanging, so it may either be something about L005 or something about running `sqlfluff fix` with multiple rules.

**Comment by alanmcruickshank** [comment]
It *could* be just very slow. The step that is really slow is the `parse` step (I think).

Try running `parse` on the same directory and see if it completes in a sensible time.

If it really does just happen with L005 and only on `fix` then can you try running it with `-vvvv` (or some other very high verbosity) to see which file it's hanging on. With large files, parsing is usually the problem but that means we've probably not flushed out many of the bugs which still exist at the parsing stage.

**Comment by barrywhart** [comment]
Ok, I narrowed down the problem. This simple file seems to cause the parser to hang:
```
SELECT
  *
  , CASE WHEN rf = 0 THEN 0 ELSE 1 END AS training
FROM
  labels
```

It seems to be this line that causes it trouble: ` , CASE WHEN rf = 0 THEN 0 ELSE 1 END AS training`, as the following, logically equivalent version of the file parses fine:

```
SELECT
  *,
  CASE WHEN rf = 0 THEN 0 ELSE 1 END AS training
FROM
  labels
```

**Comment by alanmcruickshank** [comment]
hmmmmmmm. Confirmed. Something is hanging in the `fix` step, although it manages to parse properly the first time. What's wierd is that `fix --rules L003` is fine, and `fix --rules L005` is *also* fine. I wonder if we end up in an infinite regress between the two rules.

**Comment by alanmcruickshank** [comment]
Yep. That was the problem. I've added something to catch cases like this. Interesting, once we don't let the fixing algorithm go back to a previous state, even if one rules suggest it, one of the other rules corrects accordingly, and the file fix still works. PR coming.

**Comment by barrywhart** [comment]
Thanks for the quick fix! This sounds like a "fun" one.
