### ISSUE TITLE
Add config support for leading commas?

### ISSUE THREAD

**Issue by cnolanminich** [alanmcruickshank/sqlfluff#240]
One request that would put sqlfluff entirely in line with our style guide is if we could use leading commas as a configuration to override L005 — there are plenty of style guides that recommend this, though I think they’re in the minority. 

If you’re open to it I can link to the style guides that use leading commas. 

Thanks again!

**Comment by alanmcruickshank** [comment]
Yes, I would like to support this one too. I think I'm on team trailing commas personally but I know that some people aren't.

Links to style guides would be great! They will be especially helpful in seeing exactly how people use then so that they get linted correctly.

**Comment by cnolanminich** [comment]
Here are a few examples:

* [one analyst's personal style guide](https://github.com/haleemur/sql-style-guide)
* [another analyst's style guide](https://gist.github.com/mattmc3/38a85e6a4ca1093816c08d4815fbebfb)
* [another](https://github.com/reidwil/Style_guide)
* [another](https://github.com/jgilfillan/sql_style_guide)
* [story driven SQL](https://storydrivensql.github.io/sql-style-guide/index.html#document-content/002-alignment/leading-commas)
* [personal](https://github.com/jimmywyatt/SQLStyleGuide)
* [this one presents multiple possible approaches](https://github.com/karitarr/SQL-style-guide)

I'd love to find a large company style guide that follows this convention, but so far I haven't not located any.

**Comment by cnolanminich** [comment]
Installed from `ac/rules`, and tested on production SQL with the config of . Worked like a charm! Made me realize that our style is inconsistent at the moment, linting FTW 🏆 (we are currently mixing leading commas for `select` and trailing in `in()` statements.

**Comment by alanmcruickshank** [comment]
Awesome
