### ISSUE TITLE
FileSegment error raised when using tabs

### ISSUE THREAD

**Issue by Katzmann1983** [alanmcruickshank/sqlfluff#260]
Hey,
I got the following error:

TypeError: In constructing <class 'sqlfluff.parser.segments_file.FileSegment'>, found an element of the segments tuple which isn't contigious with previous: <whitespace_RawSegment: ([4](1, 2, 2)) '\t'> > <newline_RawSegment: ([4](1, 2, 2)) '\n'>. End pos: [5](1, 2, 3). Prev String: '\t'

By using this input file 
/*
	
*/

Please note that in the comment is an invisible tab in the otherwise empty line.

**Comment by alanmcruickshank** [comment]
Confirmed. Thanks for this. I'll take a look.

**Comment by alanmcruickshank** [comment]
Thanks @Katzmann1983 - problem solved and tests are now in place to catch things like this in future.
