### ISSUE TITLE
add gitignore like configuration for files we would like to be excluded

### ISSUE THREAD

**Issue by georgim0** [alanmcruickshank/sqlfluff#270]
we've managed to do this by wrapping our sqlfluff commands with a list of files that are produced based on a .sqlfluffignore file

we've used a library that is made for this called PathSpec(https://pypi.org/project/pathspec/)

Believe this should be part of the cli as it's important to roll out linting slowly to the whole project

**Comment by alanmcruickshank** [comment]
Great suggestion @georgim0 ! Do you think it would be more natural to have a `.sqlfluffignore` file, or do you think this should become part of the standard configuration file. I can see upsides of either, but I'm curious as to which you feel is more natural?

**Comment by georgim0** [comment]
hmm.. don't feel strongly about it to be honest

i would favour the `.sqlfluffignore` approach so that is consistent with the `.gitignore`/`.dockerignore` convention so you would understand at a glance what's that file about

**Comment by alanmcruickshank** [comment]
I like that reasoning. Let's go with that.

**Comment by alanmcruickshank** [comment]
@georgim0 - PR is up. Would love your feedback on it before it gets merged! 😃

**Comment by georgim0** [comment]
Hi @alanmcruickshank

that looks great! our implementation is almost identical! 

the only difference is that we didn't go with multiple .sqlfluffignore files which is a nice feature anyway.

All good. we'll give it a go on our end and let you know if there are any issues!
