### ISSUE TITLE
Shorthand casting

### ISSUE THREAD

**Issue by Katzmann1983** [alanmcruickshank/sqlfluff#271]
Just saw that the shorthand casting being defined in the Ansi dialect as ShorthandCastSegment is actually not Ansi conform but PostgreSQL specific.

Any ideas about that?

**Comment by alanmcruickshank** [comment]
Interesting. I didn't have access to the original ansi spec to check it. Is there a different syntax for other databases or is it just not available in some dialects?

**Comment by Katzmann1983** [comment]
In Teradata (my employee) it is done for example as (DATE) '2000-01-01'.
I am not aware of it existing in Oracle.

**Comment by alanmcruickshank** [comment]
I think eventually we should create a postgres dialect and make it the default. Many common database dialects used are close derivatives of that (snowflake & redshift come time mind but probably others too). Teradata can branch directly off the root ansi dialect before all the postgres features are added.

@Katzmann1983 is this causing a bug for you at the moment or is it more that it's an annoying loophole that sqlfluff doesn't catch at the moment?
