### ISSUE TITLE
Feature Request - Add In-line Error Ignoring

### ISSUE THREAD

**Issue by gammaflauge** [alanmcruickshank/sqlfluff#292]
Sometimes rules must be broken...

It would be great if we could add a comment inline to let `sqlfluff` know to ignore a certain rule.

Maybe something like this?
```sql
select
    some_really_long_col_name -- noqa: L016
    ...
```

I pretty much stole that from how [flake8](https://flake8.pycqa.org/en/3.1.1/user/ignoring-errors.html) does it.

🙇‍♂️ thanks for considering!

**Comment by alanmcruickshank** [comment]
There's a PR for this already #284 . Should be merged this week.
