### ISSUE TITLE
Found unparsable segment @L002P001

### ISSUE THREAD

**Issue by HassanJaveed84** [alanmcruickshank/sqlfluff#300]
Using master
running `sqlfluff lint` on this sql file
```sql
SELECT column_name
FROM table1
RIGHT JOIN table2
ON table1.column_name = table2.column_name
```
results in
`L:   2 | P:   1 |  PRS | Found unparsable segment @L002P001: 'FROM table1\nRIGHT JO...'`

**Comment by alanmcruickshank** [comment]
Confirmed. Thanks for catching that. I'm adding a test case for `RIGHT JOIN` statements now to make sure that doesn't get missed in future.
