### ISSUE TITLE
Are functions not treated as keywords ?

### ISSUE THREAD

**Issue by HassanJaveed84** [alanmcruickshank/sqlfluff#304]
Not an issue, more like a question. With
```
[sqlfluff:rules:L010]
capitalisation_policy = lower
```
using sqlfluff fix --rules L010 on
```sql
SELECT MAX(id) from table
```
becomes
```sql
select MAX(id) from table
```
Shouldn't `MAX` be also lower cased ?

**Comment by alanmcruickshank** [comment]
At the moment I've got seperate rules for keywords and identifiers. Function names aren't included in either. Easy to add a rule for that though. 😁

You've made it just in time before we do a release too!

**Comment by HassanJaveed84** [comment]
Great, thanks!
