### ISSUE TITLE
unparsable section 'ALTER TABLE MODIFY COLUMN'

### ISSUE THREAD

**Issue by VQDtdr** [alanmcruickshank/sqlfluff#310]
Alter table modify column is not accepted by sqlfluff:

Found unparsable section: 'ALTER TABLE `users`\n MODIFY COLUMN\n ...':
```
ALTER TABLE `users`
    MODIFY COLUMN
    `name` varchar(255) NOT NULL,
    COMMENT "name of user";
```

**Comment by alanmcruickshank** [comment]
Thanks @VQDtdr - PR coming shortly. From your query, it also looks like you're in mysql? Given the way mysql deals with quoting you'll need to make sure your dialect is set.

As part of the PR coming, I've added a warning to make sure that if people haven't set a dialect that they get a warning about that too. 👍 

If you're able to test the new feature, I'd love to know whether it meets all your needs!

**Comment by VQDtdr** [comment]
Great, thank you very much! I'm actually missing a bit of documentation about setting the dialect. Can I do that directly from the command line using `--dialect mysql` or should I add it to the config file? Where can I find information about formatting this config file and what should be its location?

**Comment by alanmcruickshank** [comment]
You can do either of the options that you've suggested. 

As for config files: https://docs.sqlfluff.com/en/latest/configuration.html

Feel free to suggest improvements to the docs too if you feel like they're not clear too. Very happy to receive PRs for the docs.

**Comment by VQDtdr** [comment]
Thank you, I've clearly haven't been looking good enough...
