### ISSUE TITLE
Query with a group by containing a SQL-function fails to parse

### ISSUE THREAD

**Issue by johansjob** [alanmcruickshank/sqlfluff#358]
**Problem**
Queries with a group by containing a SQL-function fails to parse

**Example**
Coalesce:
```
with a as (
    select 1 as id
)
select
    coalesce(id, -1) as id
from a
group by coalesce(id, -1)

```
Timestamp_trunc:
```
with a as (
    select 1 as id, cast('2020-01-01' as timestamp) as ts
)
select
    timestamp_trunc(ts, day) as t
from a
group by timestamp_trunc(ts, day)

```

**Expected**
Successful parse :)

**Settings**
Version: 0.3.4
Dialect: BigQuery

**Comment by alanmcruickshank** [comment]
Yep. I'm also suprised that this hasn't come up before come to think of it. Thanks for the examples too @johansjob.

Should be easy to fix, we should just add `ExpressionSegment` as an additional option in `GroupByClauseSegment`. This would be a good first issue for someone, and easy to set up tests for too given the examples above.
