### ISSUE TITLE
Support for substring

### ISSUE THREAD

**Issue by flpezet** [alanmcruickshank/sqlfluff#375]
Please, could we support the `substring` (ANSI) function? 

The following query
```
select
    substring(a from 'abc') as b
from {{ref('my_table')}}
```
...results into:

```
== [test.sql] FAIL
L:  15 | P:   5 |  PRS | Found unparsable section: "substring(a from '.')"
L:  15 | P:  27 | L003 | Indentation not hanging or a multiple of 4 spaces
```

I suppose that there is a ton of ANSI functions we could support. I don't want to be annoying by raising an issue for each unsupported function I use. 
Do you have any guidelines on cases that are more important than others? I really want to contribute but I don't want to bring more noise than value by raising a lot of issues like this one.

**Comment by alanmcruickshank** [comment]
The problem here is the syntax *inside* the function rather than the function name itself. i.e. `a from 'abc'`. Happy to support this as an option however. We've already got a similar exception for `EXTRACT` like functions.
