### ISSUE TITLE
Not an issue! Surfacing a sqlfluff webapp to the community

### ISSUE THREAD

**Issue by nolanbconaway** [alanmcruickshank/sqlfluff#390]
I wrote a webapp that runs sqlfluff on SQL you paste in a web browser. I think this is likely the most interested group in something like this, so worth sharing. Let me know if there is a better spot for it.

- repo: https://github.com/nolanbconaway/sqlfluff-online
- app: https://sqlfluff-online.herokuapp.com/

Happy to relinquish the heroku app name if it is ever needed for "official" purposes!

One nice property of this is that you can share links to formatter results easily, The SQL, gzipped and b64 encoded, is a GET url parameter. Example: 

http://sqlfluff-online.herokuapp.com/fluffed?sql=H4sIAAkB-V4C_ytOzUlNLlHQUkgrys9VKOHlAgBCNckpEQAAAA%3D%3D&dialect=ansi

**Comment by alanmcruickshank** [comment]
This is awesome @nolanbconaway - I've not had much time to devote to sqlfluff over the last few weeks - but thanks for putting this together. If you're happy to - I'd love to have a link to this in the readme (feel free to credit yourself and link to your github repo if you like). Want to put a PR together to add that in?

**Comment by nolanbconaway** [comment]
Sure thing!

**Comment by alanmcruickshank** [comment]
Thanks for this @nolanbconaway - I'm going to close the issue.

Also this made me lol:
> I am not the author of Sqlfluff. Alan is, and many other contributors are (ok I opened a few PRs too). Alan never said anything like: "Nolan, hack together an online tool that makes users feel bad about their code". This is my abomination and not his.
