### ISSUE TITLE
L027 fails when referencing a field created in the select statement

### ISSUE THREAD

**Issue by pwildenhain** [alanmcruickshank/sqlfluff#396]
.sqlfluff
```
[sqlfluff:rules]
max_line_length = 115

[sqlfluff:indentation]
indented_joins = True

[sqlfluff:rules:L019]
comma_style = leading
```

test.sql
```
select
    table_1.field + table_2.field as new_field
    , new_field * 2 as final_field
from
    table_1
    inner join table_2 on table_2.key = table_1.key
```

```
$ sqlfluff lint test.sql
== [test.sql] FAIL
L:   3 | P:   7 | L027 | Unqualified reference 'new_field' found in select with
                       | more than one referenced table/view.
```

Not sure if this isn't ANSI standard, could understand if you don't want to make an exception for it

Sidenote -- is there a way to exclude rules in the `.sqlfluff` config file? I know you can use `sqlfluff lint --exclude_rules`, just hoping to not have to type that out each time

**Comment by alanmcruickshank** [comment]
On the sidenote: definitely. You can do something like below in your config file:

```
[sqlfluff]
exclude_rules = L022,L027
```

Could you review the config docs and suggest a way of making this clearer in the docs? I suspect quite a few users might not be aware of this.

As for the bug, I think this is actually the same bug as #400. `L027` doesn't have an exception at the moment for previously defined column aliases and it should.

**Comment by pwildenhain** [comment]
Sure, I can take a look at the docs -- just so I'm clear, you could specify _all_ CLI options in this way?
