### ISSUE TITLE
sqlfluff lint complains about unqualified aggregated field in HAVING statement

### ISSUE THREAD

**Issue by pwildenhain** [alanmcruickshank/sqlfluff#400]
test.sql
```sql
select
    my_table.field_1,
    max(other_table.field_2) as metric
from my_table
inner join other_table on other_table.key = my_table.key
group by
    my_table.field_1
having
    metric > 0
```

```
$ sqlfluff lint test.sql
```
Code | Line / Position | Description
-- | -- | --
L027 | 9 / 5 | Unqualified reference 'metric' found in select with more than one referenced table/view.

**Comment by alanmcruickshank** [comment]
Darn, I can totally see how this would happen. At the moment L027 doesn't have an exception for column aliases in the select.

The logic at the moment is:
1. Get all the references in the query.
2. Check whether they're qualified or not, ignore them if they are.
3. Check that it's not a reference in a USING statement.
4. Error if there are any left.

I think there should be an added step (probably between 2 and 3) to see whether it's a reference which appears as a column alias. We would need to edit `Rule_L020._eval` to make sure we get all the column references, and then pass that to `Rule_L027._lint_references_and_aliases` to make sure we can do the evaluation.

I'm also thinking that the logic in the `L020` rules and it's children is getting kind of complicated and I wonder if it needs a refactor. If you have any bright ideas on that then I'm all ears.

@pwildenhain, want to have a go at this yourself, or would you prefer not to?

**Comment by pwildenhain** [comment]
I'm definitely willing to get my hands dirty, and I'll let you know once I've gotten as far as I can 🤞
