### ISSUE TITLE
sqlfluff fails to install in Python 2.7

### ISSUE THREAD

**Issue by barrywhart** [alanmcruickshank/sqlfluff#41]
I started looking at integrating sqlfluff into our application today. We use a mixture of Python 2.7 and 3 on our projects, which new projects using Python 3.

I noticed that the package won't install in Python 2.7. It looks like a very simple issue. This is the error:
```
Collecting sqlfluff
  Using cached https://artifactory.rsglab.com/artifactory/api/pypi/pypi/packages/f3/71/6ec9f43964cb994a3b2075da1f335c021115593d9a11b3cc02ace2581ef5/sqlfluff-0.1.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-Te5lWx/sqlfluff/setup.py", line 7, in <module>
        import configparser
    ImportError: No module named configparser
```

[This module has been renamed](https://docs.python.org/2/library/configparser.html) in Python 3.
* Python 2.7: `import ConfigParser`
* Python 3: `import configparser`

I believe the following will work:
```
try:
    import configparser
except ImportError:
    import ConfigParser as configparser
```

If you use the [`six`](https://six.readthedocs.io/) library, you could instead: `from six.moves import configparser`

**Comment by barrywhart** [comment]
This is not a blocker for me -- I'll try using `sqlfluff` on one of our Python 3 projects.

**Comment by alanmcruickshank** [comment]
I'm already using the `six` module in quite a few places - great catch for finding this bug. I'm surprised that it hasn't come up in the CI tests but we should totally fix it regardless.

I like the approach of using `from six.moves import configparser` rather than importing it directly or using the `try...except...` approach. @barrywhart, fancy submitting a PR for this?

**Comment by barrywhart** [comment]
I'll create a PR. I'm very tempted to use the `try/except` technique because `setup.py` is a special case, since it runs before the package is installed. (In order to use `six` in `setup.py`, we'd have to add a `setup_requires` option to `setup.py`, in addition to the current `install_requires`.)

I don't know the current behavior of `pip`, but there have been problems in the past with `pip`'s ability to install packages that use `setup_requires`, e.g. https://github.com/pytest-dev/pytest-xdist/issues/136.
