### ISSUE TITLE
Parsing JSON and ARRAY accessors in snowflake dialect

### ISSUE THREAD

**Issue by aydumoulin** [alanmcruickshank/sqlfluff#421]
Parsing the following

```sql
SELECT
    PARSE_JSON(t.metadata)['names'][0] AS first_name,
    PARSE_JSON(t.metadata):customer_id AS customer_id
FROM tickets AS t

```

Will result in the following errors
```bash
sqlfluff lint test_json.sql
== [test_json.sql] FAIL
L:   2 | P:   5 | L013 | Column expression without alias. Use explicit `AS`
                       | clause.
L:   2 | P:  27 |  PRS | Found unparsable section: "['names'][0] AS first_name"
```

Parsing of item accessors `[n]` as well as bracket `['value']` accessors aren't handled as it seems. It seems that postgres style json-colon accessor is handled.

Here is the configuration file excerpt
```cfg
[sqlfluff]
verbose = 0
nocolor = False
dialect = snowflake
rules = None
exclude_rules = L008,L011,L019,L022,L027
recurse = 0
output_line_length = 80
```
Maybe someone could point me towards were I could start a MR from?

Thanks a lot!

**Comment by aydumoulin** [comment]
I tried uncommenting this [line](https://github.com/alanmcruickshank/sqlfluff/blob/master/src/sqlfluff/dialects/dialect_snowflake.py#L60) as it seems that `VARIANT` does support [array accessor](https://docs.snowflake.com/en/user-guide/querying-semistructured.html#retrieving-a-single-instance-of-a-repeating-element) in snowflake these days

However the linter stops without any logging 🤔

**Comment by alanmcruickshank** [comment]
Thanks for putting together such a clear Issue! :)

Would you like to put together a PR for this @aydumoulin ? Some more test queries which cover this kind of syntax would be really useful.

**Comment by aydumoulin** [comment]
I would like to try that if I manage to devote time to it. Indeed adding tests is a must.

By the way you've done great work with this parser.

**Comment by alanmcruickshank** [comment]
@aydumoulin - would you mind reviewing my PR? https://github.com/alanmcruickshank/sqlfluff/pull/442

Anything else you would add from the work that you did?

**Comment by aydumoulin** [comment]
Well it looks like you added `QUALIFY` in `ANSI` too I am not sure about the effect on MYSQL or POSTGRES

My approach was doing this work in snowflake dialect file but it did mess up with the very clean and nice heritage structure you crafted

**Comment by alanmcruickshank** [comment]
Yeah - it's a good point.

At the moment this *shouldn't* have an impacy on MySQL or POSTGRES, but there is an edge case where the word `qualify` is used as a variable name in those dialects. To be robust against that we'll need to come up with a better solution for adding the `QUALIFY` terminator to the previous clauses.

**Comment by aydumoulin** [comment]
Here was my [implementation](https://gist.github.com/aydumoulin/718f1467d60ad9b981cb27214d133ac4)
