### ISSUE TITLE
What dialects sqlfluff supports?

### ISSUE THREAD

**Issue by felipecrs** [alanmcruickshank/sqlfluff#435]
I can't find the list of supported dialects in the documentation. I wonder if this supports Oracle for example.

**Comment by greg-finley** [comment]
https://github.com/alanmcruickshank/sqlfluff/tree/master/src/sqlfluff/dialects

**Comment by felipecrs** [comment]
> https://github.com/alanmcruickshank/sqlfluff/tree/master/src/sqlfluff/dialects

Thank you so much. Perhaps the available options should be included in the `--help`?

**Comment by alanmcruickshank** [comment]
Thanks for bringing this up @felipecrs . Yeah I think this can be much better - I've just done a mini review of it. PR coming shortly, both with some documentation and an additional command to the cli.

Would you want to have a go at implementing an Oracle dialect? I'm happy to provide some pointers if you like.

**Comment by felipecrs** [comment]
> PR coming shortly, both with some documentation and an additional command to the cli.

This is awesome @alanmcruickshank!

> Would you want to have a go at implementing an Oracle dialect? I'm happy to provide some pointers if you like.

Not really... I have no experience with Oracle or PL/SQL itself. Otherwise I would surely help! I was just looking for it because I wanted to add a linter for some Oracle SQL files in my project's CI.

**Comment by alanmcruickshank** [comment]
> some Oracle SQL files in my project's CI

Can you try linting them on the `ansi` dialect and see what happens. If they don't use any advanced functions, it might work ok. I'm curious to see how it handles them. If you get parsing errors with the `ansi` dialects, try the `postgres` dialect. If neither work, then post the example queries here and we can see whether it's an easy fix to support them.

**Comment by alanmcruickshank** [comment]
@felipecrs @greg-finley - would either of you be able to review my PR? https://github.com/alanmcruickshank/sqlfluff/pull/437

**Comment by digia** [comment]
> Would you want to have a go at implementing an Oracle dialect? I'm happy to provide some pointers if you like.

Hey @alanmcruickshank, I do have a usecase for an Oracle dialect. I'd be open to giving the implementation a go, would love any pointers you could provide, first time in this realm.

**Comment by felipecrs** [comment]
FYI, the best alternative I found was https://felipezorzo.com.br/zpa/ with the [zpa-cli](https://github.com/felipebz/zpa-cli). The rules present there could help as inspiration.
