### ISSUE TITLE
Found unparsable section: 'CASE WHEN

### ISSUE THREAD

**Issue by robertdefilippi** [alanmcruickshank/sqlfluff#446]
Hello,

I'm getting an `Found unparsable section: 'CASE WHEN ((year_number % 400` error but I'm not sure what the reason why this section cannot be parsed. I think it might be the modulo inside the CASE, but I'm not sure.

Here is the section of SQL it does not like:
```
        CASE
            WHEN (year_number % 400 = 0)
            OR (year_number % 4 = 0 AND year_number % 100 != 0)
            THEN TRUE ELSE FALSE
        END AS is_leap_year,
```

And here are the full error codes for that section.

```
L:  55 | P:   9 |  PRS | Found unparsable section: 'CASE\n WHEN (year_number % 400 =
                       | 0)\n...'
L:  55 | P:   9 | L013 | Column expression without alias. Use explicit `AS`
                       | clause.
L:  56 | P:  25 |  LXR | Unable to lex characters: ''% 400 = 0)'...'
L:  57 | P:  23 |  LXR | Unable to lex characters: ''% 4 = 0 AN'...'
L:  57 | P:  41 |  LXR | Unable to lex characters: ''% 100 != 0'...'
```

Does this seem like an error with the linter, or something I'm missing.

```
$ sqlfluff version    
> 0.3.6
```

Thanks

**Comment by robertdefilippi** [comment]
I seem to have fixed the error by changing the mod symbol to the mod function

```
        CASE
            WHEN MOD(year_number, 400) = 0 OR (MOD(year_number, 4) = 0 AND MOD(year_number, 100) != 0) THEN TRUE
            ELSE FALSE
        END AS is_leap_year,
```

Does this mean `%` is not supported as a mod operator?

**Comment by alanmcruickshank** [comment]
Yep. Good catch. Modulo currently not supported.

I've just added in now. PR coming shortly. 👍 Thanks for raising this @robertdefilippi
