### ISSUE TITLE
Using with python raw sql

### ISSUE THREAD

**Issue by sobolevn** [alanmcruickshank/sqlfluff#48]
Hi! Thanks a lot for this awesome project!

Is it possible to use it with `python` code and `sql` written as strings inside?
It is pretty sad to know that these strings cannot be linted right now 😞

**Comment by alanmcruickshank** [comment]
Right now... no - but I'd be interested in working out how we might do that. Any ideas on how we could implement this?

At the moment, my best suggestion is to extract those sql statements out into seperate files when they get to a level of complexity that warrants that. If you definitely want to focus on strings inside files, then check out the sql plugin for flake8: https://github.com/pgjones/flake8-sql

**Comment by alanmcruickshank** [comment]
@sobolevn - I've had a think about this - and essentially, `sqlfluff` is a `sql` linter and not a `python` linter, and so I don't think it makes sense to this tool to be able to parse python files directly. I could see a world where sql scripts extracted from python files by *some other tool*, could then be passed to sqlfluff either on the command line or by importing some interfaces from the `sqlfluff` library if someone wanted to use `sqlfluff` as part of that.

Given that, I'm going to close this issue.
