### ISSUE TITLE
Feature Request: File based configuration

### ISSUE THREAD

**Issue by sumitkumar1209** [alanmcruickshank/sqlfluff#6]
First of all thank you @alanmcruickshank , Really nice work on authoring this project.

I wanted to know what are your plans on putting more rules or making it more configurable via JSON Config as parameter as I would like to use this in our organisation and would hate to have multiple projects to maintain internally.

Mainly around this points in your ToDos
- [ ] Configurable linting
  - [ ] Command line options for config
  - [ ] Ability to read from config files

**Comment by alanmcruickshank** [comment]
Hi @sumitkumar1209 - I've just released version 0.1.0 of sqlfluff - I'd love your feedback on it.

As for this issue - I don't expect *new* rules to added at runtime via a JSON config, but I do expect that rules could be turned on and off according to config and some more generic rules might accept some configurable parameters. For example rule L002 at the moment already has a configurable parameter for the expected indentation multiple of a line - eventually I imagine that this could be configurable in a config file and maybe through the command line.

I'm going to edit this issue to be more specific around enabling config of the dialect using a file, and to optionally be able to specify that config at runtime. I expect I'll add optional support for the usual candidates like `tox.ini` or similar too.

**Comment by alanmcruickshank** [comment]
@sumitkumar1209 - I've added this to the roadmap for 0.2.0 and started working on it. As part of this I'll aim for parity between command line options and configuration options.

For anyone interested, the first implementation of this is going to be *heavily* inspired by [what flake8 does](https://flake8.pycqa.org/en/latest/user/configuration.html#configuration-locations).
