### ISSUE TITLE
Bug: Running "sqlfluff version" on a fresh install throws an error

### ISSUE THREAD

**Issue by barrywhart** [alanmcruickshank/sqlfluff#60]
I installed `sqlfluff` and ran the `version` and `lint` commands. Both failed, probably due to a missing configuration file. It would be good to report this error in a nicer way.

Here's the result I saw:
```
$ sqlfluff version
Traceback (most recent call last):
  File "/usr/local/pyenv/versions/3.7.3/bin/sqlfluff", line 11, in <module>
    load_entry_point('sqlfluff==0.2.1', 'console_scripts', 'sqlfluff')()
  File "/usr/local/pyenv/versions/3.7.3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/pyenv/versions/3.7.3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/pyenv/versions/3.7.3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/pyenv/versions/3.7.3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/pyenv/versions/3.7.3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/pyenv/versions/3.7.3/lib/python3.7/site-packages/sqlfluff/cli/commands.py", line 82, in version
    c = get_config(**kwargs)
  File "/usr/local/pyenv/versions/3.7.3/lib/python3.7/site-packages/sqlfluff/cli/commands.py", line 55, in get_config
    return FluffConfig.from_root(overrides=overrides)
  File "/usr/local/pyenv/versions/3.7.3/lib/python3.7/site-packages/sqlfluff/config.py", line 283, in from_root
    return cls(configs=c, overrides=overrides)
  File "/usr/local/pyenv/versions/3.7.3/lib/python3.7/site-packages/sqlfluff/config.py", line 263, in __init__
    if self._configs['core']['rules']:
KeyError: 'rules'
```

**Comment by barrywhart** [comment]
I get the same error running the suggested example from the docs:
```
$ echo "  SELECT a  +  b FROM tbl;  " > test.sql
$ sqlfluff lint test.sql
```

**Comment by barrywhart** [comment]
I did some digging in the source code. I did not have any of these files in my user directory:
`['setup.cfg', 'tox.ini', 'pep8.ini', '.sqlfluff']`. I guess that's why it failed. Maybe there needs to be a default configuration object as a fallback?

**Comment by barrywhart** [comment]
I found [this page](https://github.com/alanmcruickshank/sqlfluff/blob/master/docs/source/configuration.rst) in the docs, which is intended to include a default configuration file. It looks like something is a bit wrong with how it's including the actual config file, because it's rendering as:

```
.. literalinclude:: ../../src/sqlfluff/default_config.cfg
   :language: cfg
   :linenos:
```

I do see the filename `sqlfluff/default_config.cfg`, and I'll manually copy that file to `~/.sqlfluff` as a workaround.

**Comment by barrywhart** [comment]
Related request: Would it be possible to allow the main configuration file (e.g. `.sqlfluff`) to be located some place other than `~`? In our dev environment, `~` is inside a temporary Docker container and the app repo is mounted at `~/src`. It will be much more convenient to place the config file at `~/src/.sqlfluff` so we don't have to play games with the container's root directory.

**Comment by alanmcruickshank** [comment]
*On the first thing*
Great catch, yes it's because there aren't default values for those config values. You shouldn't *require* a config file unless you want to change the default config. I'm just pushing a fix now and will release a new version shortly. Once 0.2.2 is out can you test it for this issue?

*On the second thing*
@barrywhart - you can *also* put the main config file in the main directory that you're running sqlfluff from. So if you `cd` into `~/src` then run `sqlfluff` then it will pull the config from that root (and the user directory if it finds a file there). Does that solve the issue or do you need the ability to specify a config file on the command line? Happy to implement that if needed. The precedence rules for config are here: https://sqlfluff.readthedocs.io/en/latest/configuration.html#nesting

**Comment by alanmcruickshank** [comment]
@barrywhart - 0.2.2 is live on github and pypi:
https://github.com/alanmcruickshank/sqlfluff/releases/tag/0.2.2
https://pypi.org/project/sqlfluff/

Can you test to see if this issue is fixed?

**Comment by barrywhart** [comment]
>you can also put the main config file in the main directory that you're running sqlfluff from. So if you cd into ~/src

I thought I tried this, but I may have gotten it wrong. When you say "main config file", can that be any of the 4 filenames? I'll try again and capture the steps more carefully.

**Comment by alanmcruickshank** [comment]
Ah - I think the wording is a little confusing. I also suspect that there's another issue at play here. I've just fixed it in 0.2.3 (also live now).

- You shouldn't need *any* config file to run sqlfluff without raising an error.
- *if you do* want to use a config file to overwrite any values, then sqlfluff will look in the following locations in order, and at each stage any configs found will *patch* previous ones, so you'll end up with a combination of all of the values:
  1. [and this one doesn't really count] - there's a default config as part of the sqlfluff package. *or at least it is now 🙄 *
  2. It will look in the users home directory (`~`) for any of `setup.cfg`, `tox.ini`, `pep8.ini` or `.sqlfluff`. If it finds more than one it will use them in that order.
  3. It will look for the same 4 files in the current working directory.
  4. [*if parsing a file in a subdirectory of the current working directory*] it will look for the same four files in every subdirectory between the current working dir and the file directory.
  5. It will look for the same 4 files in the directory containing the file being linted.

Do you reckon that I should re-word the docs? I think they're a bit confusing.

**Comment by alanmcruickshank** [comment]
@barrywhart - new release is live again: https://github.com/alanmcruickshank/sqlfluff/releases/tag/0.2.3

Would love it if you could test for the same issue. 😄

**Comment by barrywhart** [comment]
I tested 0.2.3 and confirm it works:
* If there's no config file
* If there's a config file in the current directory (and no config file in `~`)

**Comment by barrywhart** [comment]
I agree it's worth updating the documentation to clarify that files found in later stages patch previous ones, rather than replacing them (as you did above).

I think you want to use the word "override" rather than "overwrite" (IIUC, they mean slightly different things -- the former is more of a logical replacement, while "overwrite" can be interpreted to mean the file is actually being replaced on disk.)

Did you have any other changes in mind?
