### ISSUE TITLE
Unexpected behavior of 'sqlfluff fix' for "Indentation length is not a multiple of 4"

### ISSUE THREAD

**Issue by barrywhart** [alanmcruickshank/sqlfluff#68]
Fixing indentation issues in this file ends up moving the incorrectly indented text left (unindenting it) rather than right (moving it to the indentation I expected).

Input:
```
SELECT
  user_id,
  list_id,
    gender_label,
    audience
FROM
  age_data
JOIN
    gender_data
USING
  (user_id, list_id)
JOIN
  audience_size
USING
  (user_id, list_id)
LEFT JOIN
  verts
USING
  (user_id)
```

Output:
```
SELECT
user_id,
list_id,
    gender_label,
    audience
FROM
age_data
JOIN
    gender_data
USING
(user_id, list_id)
JOIN
audience_size
USING
(user_id, list_id)
LEFT JOIN
verts
USING
(user_id)
```

Is there a way to have it deduce and apply the correct indentation based on the structure of the query?

Expected output:
```
SELECT
    user_id,
    list_id,
    gender_label,
    audience
FROM
    age_data
JOIN
    gender_data
USING
    (user_id, list_id)
JOIN
    audience_size
USING
    (user_id, list_id)
LEFT JOIN
    verts
USING
    (user_id)
```

**Comment by alanmcruickshank** [comment]
Yeah this is a bit crufty at the moment. I think you've hit the nail on the head, that we need to deduce the *correct* indentation to do this. At the moment we just dumbly round to the nearest 4.

I think this requires that document outlining the *correct* indentation as I mentioned in #76 .

**Comment by alanmcruickshank** [comment]
I'll be addressing this as part of #91. Discussion will go there.
