### ISSUE TITLE
Looking for contributors?

### ISSUE THREAD

**Issue by barrywhart** [alanmcruickshank/sqlfluff#7]
Are you still developing this project, and are you looking for contributors? I am a data engineer at Mailchimp, and we make extensive use of BigQuery.

A tool like this could be helpful for our team, and we may be able to help with development if you're still planning to work on it.

Please let me know -- thanks!

**Comment by alanmcruickshank** [comment]
Hi Barry,

Yes I'm still working on it - I've been rewriting the whole project from
the ground up though so I might need to get that live before it can be very
useful. Once that's up I'd love some help developing it.

Once we get to that point I'd love some help with contributors. Can you
raise an issue on the github, with an example query that you'd like to find
some linting errors in? That will be a great reminder and a way of tagging
you in the progress.

thanks for getting in touch!

Alan

**Comment by nolanbconaway** [comment]
I love this tool! Please keep me posted when the project is ready for new contributors!

**Comment by alanmcruickshank** [comment]
@barrywhart @nolanbconaway  - we're open for business again. I'd love your feedback on the most recent 0.1.0 release and I'd welcome any help in either debugging the new implementation, submitting feature requests or even submitting pull requests now. 😃 

I'm going to close this issue now that the doors are open again 👍

**Comment by mrshu** [comment]
Just came here to say that I also very much appreciate all the work you've put into `sqlfluff` @alanmcruickshank and although we have to use `0.0.7` for now (the `0.1.*` release does not seem to work for us for now -- see some of the issues I've posted), I would be very happy to help!

**Comment by alanmcruickshank** [comment]
@mrshu - thanks for being so kind. I'll try and prioritise your issues so I can help you get `0.1.*` into production. If any other issues come up, do bring them up!

**Comment by barrywhart** [comment]
@alanmcruickshank: I am interested in contributing -- this is an exciting project! We've had some recent re-org at work, and process/code quality tools like this are definitely part of our team's domain (we're an ML Engineering team), but we're supporting several active data science projects as well. I hope to find time for long-term investments like this along with the project work. 💯

**Comment by alanmcruickshank** [comment]
@barrywhart - great to hear that you're keen to get involved. What would be *most* useful right now is to try and get the `0.1.*` version running in the wild as part of your deployment pipeline (or at least as part of your workflow). As you do that I'm sure you'll find a few bugs at this stage - can you post them as issues on github, and we can work together on prioritising them. I'd love to find a couple that you feel comfortable taking a stab at and then we can move even faster.

**Comment by barrywhart** [comment]
Ok, I added a ticket for this to our backlog. If things work out, I'm hoping to find at least a couple hours a week to work on this tool. Exciting!
