### ISSUE TITLE
Rule: Warn if a query uses both DISTINCT and GROUP BY

### ISSUE THREAD

**Issue by barrywhart** [alanmcruickshank/sqlfluff#9]
Since these two features of SQL behave very similarly, to my knowledge there is no reason to use both in the same query (I have not been able to 100% confirm this.). Even if there are occasional reasons, it's still pretty unusual and worth flagging.

If someone does this, they may be misunderstanding the behavior. The tool should suggest they eliminate `DISTINCT` from the query and do what they need using `GROUP BY`.

**Comment by alanmcruickshank** [comment]
Great Idea 👍
